services:
  - type: web
    name: crazy-8-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0 # Or whatever recent version is standard
    autoDeploy: true
